package:
  name: ncvis
  version: 0.0.4

source:
  - path: ../ 
  # git_rev: travis-setup
  # git_url: https://github.com/alartum/nÐ•cvis
  - git_url: https://github.com/imneme/pcg-cpp.git
    folder: lib/pcg-cpp
  - git_url: https://github.com/nmslib/hnswlib.git
    folder: lib/hnswlib


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp     # [osx]
  host:
    - python
    - setuptools
    - numpy >=1.15
    - cython >=0.29
  run:
    - python
    - numpy >=1.15
    - scipy >=1.1
test:
  imports:
    - ncvis

about:
  license_file: LICENSE
  summary: NCVis is an efficient solution for data visualization
  dev_url: https://github.com/alartum/ncvis