language: python

env:
  - OMP_NUM_THREADS=4

matrix:
  include:
    - name: "Linux"
      dist: xenial
      install:
        - pip3 install --upgrade pip
        - pip3 install numpy cython
        - make lib
      script:
        - make wrapper