branches:
  only:
  - master
  - /^release-.*$/

language: python
env:
  - OMP_NUM_THREADS=4

matrix:
  include:
    - name: "Xenial Linux"
      python: 3.7 
      dist: xenial
    - name: "macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
    
before_install: bash travis/before_install.sh
install: bash travis/install.sh
# install:
#   - pip3 install --upgrade pip
#   - pip3 install numpy cython
#   - make lib
# script:
#   - make wrapper
script:
  - echo "Sample script"