language: minimal

matrix:
  include:
    - name: "Linux"
      dist: xenial
      install:
        - pip3 install --upgrade pip
        - pip3 install numpy cython
        - make lib
      script:
        - pip3 install -v -e .