branches:
  only:
  - master
  - /^release-.*$/

language: python
env:
  global:
    - OMP_NUM_THREADS=4

matrix:
  include:
    - name: "Linux Python 3.6"
      dist: xenial
      env: CONDA_NAME=Linux CONDA_EXT=sh SCRIPT_EXT=sh CONDA_PYTHON_VERSION=3.6

    - name: "Linux Python 3.7"
      dist: xenial
      env: CONDA_NAME=Linux CONDA_EXT=sh SCRIPT_EXT=sh CONDA_PYTHON_VERSION=3.7

    - name: "macOS Python 3.6"
      os: osx
      osx_image: xcode10.2
      language: shell
      env: CONDA_NAME=MacOSX CONDA_EXT=sh SCRIPT_EXT=sh CONDA_PYTHON_VERSION=3.6

    - name: "macOS Python 3.7"
      os: osx
      osx_image: xcode10.2
      language: shell
      env: CONDA_NAME=MacOSX CONDA_EXT=sh SCRIPT_EXT=sh CONDA_PYTHON_VERSION=3.7

    - name: "Windows Python 3.6"
      os: windows
      language: shell
      env: CONDA_NAME=Windows CONDA_EXT=exe SCRIPT_EXT=cmd CONDA_PYTHON_VERSION=3.6

    - name: "Windows Python 3.7"
      os: windows
      language: shell
      env: CONDA_NAME=Windows CONDA_EXT=exe SCRIPT_EXT=cmd CONDA_PYTHON_VERSION=3.7

before_install: 
  - echo $CONDA_UPLOAD_TOKEN > conda_token.txt
  - curl "https://repo.anaconda.com/miniconda/Miniconda3-latest-$CONDA_NAME-x86_64.$CONDA_EXT" -o ~/miniconda.$CONDA_EXT
  - travis/before_install.$SCRIPT_EXT
  
install: travis/install.$SCRIPT_EXT
script: travis/build.$SCRIPT_EXT
after_success: if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_EVENT_TYPE = 'push' ]; then travis/upload.$SCRIPT_EXT; fi