env:
  - OMP_NUM_THREADS=4

matrix:
  include:
    - name: "Linux"
      dist: xenial
      language: python
    - name: "macOS"
      os: osx
      language: shell

install:
  - pip3 install --upgrade pip
  - pip3 install numpy cython
  - make lib
script:
  - make wrapper