language: minimal

matrix:
  include:
    - name: "Linux"
      dist: xenial
      install:
        - sudo apt-get install pip3
        - pip3 install --upgrade pip
        - pip3 install numpy cython
        - make lib
      script:
        - make wrapper