trigger:
- master

extends:
  template: azure-conda.yml
  parameters:
    platforms:
      - name: 'Linux'
        image: 'ubuntu-latest'
      - name: 'Windows'
        image: 'windows-latest'
      - name: 'macOS' 
        image: 'macOS-latest'
    pythonVersions:
      - '3.7'