parameters:
  - name: platforms
    type: object
    default: []
  - name: pythonVersions
    type: object
    default: []

jobs:
  - job:
    strategy:
      matrix:
        ${{ each platform in parameters.platforms }}:
          ${{ each pythonVersion in parameters.pythonVersions }}:
            ${{ platform.name }} Python ${{ pythonVersion }}:
              pool: ${{ platform.image }}
              python.version: ${{ pythonVersion }}
    steps:
    - script: git submodule update --init --recursive
      displayName: Download submodules

    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH

    - script: | 
        conda config --set always_yes yes --set anaconda_upload no
        conda update -q conda
        conda create -n test python=$(python.version) conda-build conda-verify
      displayName: Create environment

    - script: |
        source activate test
        conda-build --no-test .
        CONDA_PKG=$(conda-build --output .)
        echo "##vso[task.setvariable variable=CONDA_PKG]$CONDA_PKG"
      displayName: Build
    
    - script: |
        source activate test
        conda-build -t $CONDA_PKG
      displayName: Test