parameters:
  - name: pythonVersions
    type: object
    default: []

  - name: platforms
    type: object
    default: ['linux', 'macos', 'windows']

jobs:
- template: azure_templates/${{ each platform in parameters.platforms }}.yml
  parameters:
    pythonVersions:
      ${{ each pythonVersion in parameters.pythonVersions }}:
        - ${{ pythonVersion }}